//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Camera_load
    {
        public System.DateTime date { get; set; }
        public bool status { get; set; }
        public string state_number { get; set; }
        public string img { get; set; }
    }
}
