//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fuel_List
    {
        public Nullable<int> Station_ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> AmountOfFuel { get; set; }
        public int ID { get; set; }
    
        public virtual Gas_Station_ID Gas_Station_ID { get; set; }
    }
}
