//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gas_Station
    {
        public int ID { get; set; }
        public string Gas_station1 { get; set; }
    
        public virtual Gas_Station_ID Gas_Station_ID { get; set; }
    }
}
