//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loyalty_Сards
    {
        public int LoyaltyСard { get; set; }
        public string CardHolder { get; set; }
        public short Balance { get; set; }
    }
}
