//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GasStationdbEntities : DbContext
    {
        public GasStationdbEntities()
            : base("name=GasStationdbEntities")
        {
        }
        protected static GasStationdbEntities _context;
        public static GasStationdbEntities GetContext() {
            if (_context == null) {
                _context = new GasStationdbEntities();
            }
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CreditCard> CreditCard { get; set; }
        public virtual DbSet<DepositCard> DepositCard { get; set; }
        public virtual DbSet<Fuel_List> Fuel_List { get; set; }
        public virtual DbSet<Gas_Station> Gas_Station { get; set; }
        public virtual DbSet<Gas_Station_ID> Gas_Station_ID { get; set; }
        public virtual DbSet<Loyalty_Сards> Loyalty_Сards { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Camera_load> Camera_load { get; set; }
    }
}
